name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_S3_BUCKET_STATIC: "widget-upload-web-static"
  AWS_S3_BUCKET_CDN: "widget-upload-web-static-cdn"
  SOURCE_DIST: "./dist"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        id: install-dependencies
        run: |
          pnpm install

      - name: Build app
        id: build-app
        run: |
          pnpm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync to S3 Static
        id: sync-to-s3-static
        run: |
          aws s3 sync ${{env.SOURCE_DIST}} s3://${{env.AWS_S3_BUCKET_STATIC}} --delete --exclude '.*git*'

      - name: Sync to S3 CDN
        id: sync-to-s3-cdn
        run: |
          aws s3 sync ${{env.SOURCE_DIST}} s3://${{env.AWS_S3_BUCKET_CDN}} --delete --exclude '.*git*'
      
      - name: Invalidate CloudFront Cache
        id: invalidate-cloudfront-cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"